image:
- Visual Studio 2017
install:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
- cmd: set PATH=%PATH%;C:\Qt\5.12.1\msvc2017_64\bin;
build_script:
- cmd: qmake allie.pro
- cmd: nmake
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

